### ISSUE TITLE
请问需要除了取消订阅   需要手动close  websocket吗？

### ISSUE THREAD

**Issue by xinyangmaojian** [dhhAndroid/RxWebSocket#10]
源码中doOnDispose()方法只是把url从map中remove掉了，比如我需要在ondetory方法中关闭掉websocket连接，是直接取消订阅即可  还是需要关闭连接 再取消订阅？
 /**
     * @param url      ws://127.0.0.1:8080/websocket
     * @param timeout  The WebSocket will be reconnected after the specified time interval is not "onMessage",
     *                 <p>
     *                 在指定时间间隔后没有收到消息就会重连WebSocket,为了适配小米平板,因为小米平板断网后,不会发送错误通知
     * @param timeUnit unit
     * @return
     */
    public Observable<WebSocketInfo> getWebSocketInfo(final String url, final long timeout, final TimeUnit timeUnit) {
        Observable<WebSocketInfo> observable = observableMap.get(url);
        if (observable == null) {
            observable = Observable.create(new WebSocketOnSubscribe(url))
                    //自动重连
                    .timeout(timeout, timeUnit)
                    .retry()
                    //共享
                    .doOnDispose(new Action() {
                        @Override
                        public void run() throws Exception {
                            observableMap.remove(url);
                            webSocketMap.remove(url);
                            if (showLog) {
                                Log.d("RxWebSocketUtil", "注销");
                            }
                        }
                    })
                    .doOnNext(new Consumer<WebSocketInfo>() {
                        @Override
                        public void accept(WebSocketInfo webSocketInfo) throws Exception {
                            if (webSocketInfo.isOnOpen()) {
                                webSocketMap.put(url, webSocketInfo.getWebSocket());
                            }
                        }
                    })
                    .share()
                    .subscribeOn(Schedulers.io())
                    .observeOn(AndroidSchedulers.mainThread());
            observableMap.put(url, observable);
        } else {
            observable = Observable.merge(Observable.just(new WebSocketInfo(webSocketMap.get(url), true)), observable);
        }
        return observable;

**Comment by dhhAndroid** [comment]
不需要，在RxJava取消订阅的时候，会close websocket
`https://github.com/dhhAndroid/RxWebSocket/blob/612a2ebd0616843ed9c07679bbc9e38261ffff7c/websocket2/src/main/java/com/dhh/websocket/RxWebSocketUtil.java#L334`

**Comment by dhhAndroid** [comment]
不需要，在RxJava取消订阅的时候，会close websocket
[https://github.com/dhhAndroid/RxWebSocket/blob/612a2ebd0616843ed9c07679bbc9e38261ffff7c/websocket2/src/main/java/com/dhh/websocket/RxWebSocketUtil.java#L334](url)

**Comment by dhhAndroid** [comment]
@xinyangmaojian 不需要，在RxJava取消订阅的时候，WebSocket会自动关闭
[点击查看代码](https://github.com/dhhAndroid/RxWebSocket/blob/612a2ebd0616843ed9c07679bbc9e38261ffff7c/websocket2/src/main/java/com/dhh/websocket/RxWebSocketUtil.java#L334)
