### ISSUE TITLE
有判断websocket连接状态的方法吗

### ISSUE THREAD

**Issue by kong-jing** [dhhAndroid/RxWebSocket#11]
webSocketInfo.isOpen()，最开始我以为这个可以判断。但是好像不能通过这个来做判断。

**Comment by kong-jing** [comment]
`boolean isConnected = mWebSocketInfo.getWebSocket().send("");`
现在我使用这个来获取连接状态

**Comment by dhhAndroid** [comment]
@kong-jing 你好,感谢你反馈bug,新版本我已经修复这个问题,请使用1.5.0版本.判断WebSocket连接状态还是用那个webSocketInfo.isOpen(),这个东西只有在WebSocket在开启的时候发送一个true,其他情况都是false.
另外项目封装了WebSocketSubscriber和WebSocketAction1,你可以仿照这两个进行扩展.[点击查看WebSocketSubscriber用法](https://github.com/dhhAndroid/RxWebSocket/blob/f621e9aae138dcb1d10318c02177dd655328e3e5/demo/src/main/java/com/dhh/rxwebsocket/MainActivity.java#L81l)
[点击查看WebSocketAction1用法](https://github.com/dhhAndroid/RxWebSocket/blob/f621e9aae138dcb1d10318c02177dd655328e3e5/demo/src/main/java/com/dhh/rxwebsocket/MainActivity.java#L100)

**Comment by dhhAndroid** [comment]
@kong-jing 你试一下效果,给我反馈一下,谢谢!

**Comment by kong-jing** [comment]
我试试
换了`new WebSocketSubscriber() {`这个扩展，`webSocketInfo.isOpen()`这个暂时没用了，确实是只有发送信息给客户端之后成功打开连接了才会发送*true*,只要接收到了`onMessage` ,则会变成false。
之前是在测试下websocket断网情况下`webSocketInfo.isOpen()`的值，通过这个来进行提示。

不知道是否和 okhttp3 一样websocket，会有请求失败的状态[okhttp3](https://github.com/square/okhttp/blob/d854e6d5ad93da4da9b5d5818ee752477e501b18/samples/guide/src/main/java/okhttp3/recipes/WebSocketEcho.java#L39)
@dhhAndroid

**Comment by dhhAndroid** [comment]
@kong-jing 你指的是连接失败,还是发送失败?这个库底层就是okhttp的WebSocket实现的.不过官方的demo很老了,我用的最新的okhttp3.9.0写的.这个库,Observable下游是接收不到WebSocket连接失败的事件的,因为连接失败的话上游就做了重连处理.把错误吃掉了.

**Comment by kong-jing** [comment]
@dhhAndroid 我指的是类似网络中断或者后台服务挂掉导致 websocket 断开的情况，只是想在这个情况发生后得到通知。嗯，了解了，看来下游拿不到这个事件。

**Comment by dhhAndroid** [comment]
@kong-jing 我就是在异常断开的时候，重连的。你是想拿到这个错误通知吗？我改下就能实现。

**Comment by kong-jing** [comment]
@dhhAndroid 嗯，我想拿到这个。
