### ISSUE TITLE
ping帧（心跳包）如何发送？

### ISSUE THREAD

**Issue by houseDream** [dhhAndroid/RxWebSocket#12]

**Comment by dhhAndroid** [comment]
这个是基于okhttp3写的,我看了源码,对外没有暴露心跳包方法,你可以查看一下okhttp相关文档,如果有好的方法实现ping,及时issue告诉我,谢谢!

**Comment by dhhAndroid** [comment]
@houseDream 可以用另外的方式实现类似心跳的功能,比如你这边主动send("ping")消息,让服务的给你返回对应的pong,或者你不用发,让服务端定期给你发送pong等,都是可以实现的.下个版本我把断连事件也传递下来.
