### ISSUE TITLE
会出一个简化版无rx的牌本吗

### ISSUE THREAD

**Issue by 1371030** [dhhAndroid/RxWebSocket#13]
会出一个简化版无rx的牌本吗

**Comment by dhhAndroid** [comment]
什么原因呢？

**Comment by 1371030** [comment]
1,小白可以使用，调试简单
2,本着简单稳定，资源消耗少
3,或者使用独立的websocket模块，okhttp还是庞大

不知道说的可有道理，小白请勿见怪

**Comment by dhhAndroid** [comment]
@1371030 我个人认为现在okhttp应该是目前应用比较广泛的网络请求框架了，所以这个没必要精简，一般项目里原来都会有的。至于RxJava，如果不熟悉的话，按我readme的文档使用就可以了。所以不打算精简了。
