### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by zouxianbincc** [dhhAndroid/RxWebSocket#16]
换成自己的URL时，URL是https
"https://xxx.xxx.cc/api/socket/opensocket?nickName=3320229879"

就会报
 E/RxWebSocketUtil: java.net.ProtocolException: Expected HTTP 101 response but was '400 Bad Request'/api/socket/opensocket

**Comment by dhhAndroid** [comment]
你这个不是WebSocket连接吧， WebSocket连接是ws:// 或 wss:// 开头的，不是https

**Comment by zouxianbincc** [comment]
这是我们服务器的地址，现在用webSocket 也是这个，能正常联接的接收

**Comment by zouxianbincc** [comment]
Java WebSocket
