### ISSUE TITLE
添加 implementation 'com.dhh:websocket2:2.1.2' 显示Failed to resolve: com.dhh:websocket2:2.1.2

### ISSUE THREAD

**Issue by zhyon404** [dhhAndroid/RxWebSocket#18]
implementation 'com.dhh:websocket:2.1.2' 可以，any idea？

**Comment by dhhAndroid** [comment]
@zhyon404 请问你使用的是Android studio 吗？以及版本是多少 ？implementation是AS3.+的用法，compile是3.0一下的用法，试一下是否能够解决

**Comment by zhyon404** [comment]
@dhhAndroid Android studio3.1.1 , compile 也不行，用implementation是没问题的，因为其他依赖是这样用的。

**Comment by dhhAndroid** [comment]
@zhyon404 这个库是Android平台的，内部有Android代码。gradle构建的项目应该都能用吧

**Comment by zhyon404** [comment]
@dhhAndroid  我在jcenter只搜索到 com.dhh:websocket，没有com.dhh:websocket2，会不会是这个原因。
见：
https://bintray.com/dhhandroid/maven/rxwebsocket

**Comment by zhyon404** [comment]
@dhhAndroid 仔细找了一下，找到了websocket2，https://bintray.com/dhhandroid/maven/RxWebSocket2
，发现它的最高版本是2.1.1，改成这样好用了，3q

**Comment by dhhAndroid** [comment]
@zhyon404 非常抱歉，我现在看清楚问题了，RxJava2版本，代码我没有2.1.2版本，我代码提交到github上了，但是忘记提交到maven上了，我现在提交一下

**Comment by zhyon404** [comment]
@dhhAndroid ok, 3q very much, nice work btw. :grinning:
