### ISSUE TITLE
你好 我在Fragment里面使用报java.lang.IllegalStateException: FragmentManager is already executing transactions

### ISSUE THREAD

**Issue by yonglf** [dhhAndroid/RxWebSocket#23]

**Comment by dhhAndroid** [comment]
@yonglf 所报错误，应该不是本库导致的。可否帖一下调用代码？这个错误是fragment添加到Activity时报的错误

**Comment by yonglf** [comment]
RxWebSocket.get(HttpCode.API_WS_THIRT_SECOND)
                .compose(RxLifecycle.with(this).<WebSocketInfo>bindToLifecycle())
                .subscribe(new WebSocketSubscriber() {
                    @Override
                    protected void onOpen(WebSocket webSocket) {
                        super.onOpen(webSocket);
                        LogUtils.e("onOpen");
                    }

                    @Override
                    protected void onMessage(String text) {
                        super.onMessage(text);
                        LogUtils.e("onMessage = " + text);
                        try {
                            JSONObject socketJson = new JSONObject(text);
                            int type = socketJson.getInt("type");
                            String data = socketJson.getString(MobileConstants.DATA);
                            LogUtils.e("30s Socket data = " + data);
                            ThirtySecondSocket tss = ParseUtils.parseJsonObject(data, ThirtySecondSocket.class);
                            if (tss != null) {
                                if (type == 1 || type == 2) {//1报名2取消
                                    isOpen(tss);
                                } else if (type == 3) {
                                    Message message = new Message();
                                    message.what = 0;
                                    message.obj = tss;
                                    handler.sendMessage(message);
                                } else if (type == 5) {//拍卖结束
                                    Message message = new Message();
                                    message.what = 1;
                                    message.obj = tss;
                                    handler.sendMessage(message);
                                }
                            }
                        } catch (JSONException e) {
                            e.printStackTrace();
                        }
                    }

                    @Override
                    protected void onMessage(ByteString byteString) {
                        super.onMessage(byteString);
                    }

                    @Override
                    protected void onReconnect() {
                        super.onReconnect();
                        LogUtils.e("onReconnect");
                    }

                    @Override
                    protected void onClose() {
                        super.onClose();
                        LogUtils.e("onClose");
                    }

                    @Override
                    public void onError(Throwable e) {
                        super.onError(e);
                        LogUtils.e("onError = " + e);
                    }
                });

**Comment by yonglf** [comment]
我写在Fragment里面的

**Comment by yonglf** [comment]
@dhhAndroid 报错的位置.compose(RxLifecycle.with(this).<WebSocketInfo>bindToLifecycle())

**Comment by dhhAndroid** [comment]
@yonglf 没有看我这个项目：[RxLifecycle](https://github.com/dhhAndroid/RxLifecycle) 的readme？按文档集成一下，这个项目我在公司的项目里一直在用，并且在fragment里用也没有遇到上述问题。试一下：
```java
compose(RxLifecycle.with(this).bindOnDestroy())
```
如果真不行，就先不用这个RxLifecycle库了，自己手动注销吧

**Comment by dhhAndroid** [comment]
@yonglf 你是不是在ViewPager里添加的fragment ？[点击查看这个连接，是否能够解决问题](https://segmentfault.com/q/1010000007719092)

**Comment by yonglf** [comment]
@dhhAndroid 是的

**Comment by dhhAndroid** [comment]
@yonglf [点击查看这个连接，是否能够解决问题](https://segmentfault.com/q/1010000007719092)

**Comment by dhhAndroid** [comment]
@yonglf 问题是否解决？
