### ISSUE TITLE
OPPO R9sk一直执行onReconnect方法，其他手机却可以连接

### ISSUE THREAD

**Issue by lzy6** [dhhAndroid/RxWebSocket#26]
OPPO R9sk  Android6.0  连不上长链接，一直重连执行onReconnect方法，onError没有进，看不到错误日志，其他手机却可以连接。

**Comment by lzy6** [comment]
前端看不到什么，通过后台在重连的时候重连一次后台打印一次这个
SSL handshake error: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown

**Comment by lzy6** [comment]
这个问题解决了，设置setSSLSocketFactory这个就可以了

**Comment by dhhAndroid** [comment]
@lzy6 对，后台报的错误是ssl握手失败
