### ISSUE TITLE
onNext消息被覆盖

### ISSUE THREAD

**Issue by kailaisi** [dhhAndroid/RxWebSocket#3]
当发送消息过快时，stringInfo用的是同一个对象，如果在第一个onNext未执行的时候，第二个消息到来，会把之前的stringInfo信息覆盖，导致前一条数据丢失

**Comment by dhhAndroid** [comment]
@kailaisi 我这么做是有原因的,因为socket推送消息比较频繁,是为了避免重复创建WebSocketInfo对象,之前是想用对象池实现,但是调用者增加了回收WebSocketInfo的操作,你这个是在什么用途?如果必须要接受到每条数据的话,我就更改一下,重新发个版本.

**Comment by kailaisi** [comment]
when it connected,the server while send two different infos to the client .
 I have resolve it by myself .
 just to tell you where the problem is .
