### ISSUE TITLE
报错java.lang.Throwable:The mapper function returned a null value.

### ISSUE THREAD

**Issue by BigBrother2018** [dhhAndroid/RxWebSocket#31]
java.lang.Throwable:The mapper function returned a null value.
--
2 io.reactivex.internal.functions.ObjectHelper.requireNonNull(ObjectHelper.java:39)
3 ......
4 Caused by:
5 java.lang.Throwable:
6 io.reactivex.Observable.map(Observable.java:8814)
7 com.demo.common.rxwebsocket.RxWebSocketUtil.getWebSocket(RxWebSocketUtil.java:222)
8 com.demo.common.rxwebsocket.RxWebSocketUtil.asyncSend(RxWebSocketUtil.java:271)
9 com.demo.common.rxwebsocket.RxWebSocket.asyncSend(RxWebSocket.java:77)
10 com.demo.ui.contact.jobs.GetContactInfoJob.onRun(GetContactInfoJob.java:69)
11 com.birbit.android.jobqueue.Job.safeRun(Job.java:229)

public Observable<WebSocket> getWebSocket(String url) {
        return getWebSocketInfo(url)
                .map(new Function<WebSocketInfo, WebSocket>() {
                    @Override
                    public WebSocket apply(@NonNull WebSocketInfo webSocketInfo) throws Exception {
                        return webSocketInfo.getWebSocket();
                    }
                });
    }
getWebSocketInfo(url)这一行报错了，怎么解决？

**Comment by dhhAndroid** [comment]
这个是RxJava2的特性，map操作符，不允许返回空数据，应该数据框架内部的bug，你先调用其他方法，下个版本我会修复，感谢提issues

**Comment by dhhAndroid** [comment]
2.1.3版本已经修复 @BigBrother2018
