### ISSUE TITLE
接收数据异常

### ISSUE THREAD

**Issue by YinWuteng** [dhhAndroid/RxWebSocket#32]
当webSocket数据频率很快是，就会报出rx.exceptions.MissingBackpressureException 的异常

**Comment by dhhAndroid** [comment]
RxJava的常见错误，出现了背压错误，请问 你用的是RxJava1还是RxJava2的版本？，以及这个数据频率很快的WebSocket连接发送的数据，是否允许丢失？

**Comment by YinWuteng** [comment]
> RxJava的常见错误，出现了背压错误，请问 你用的是RxJava1还是RxJava2的版本？，以及这个数据频率很快的WebSocket连接发送的数据，是否允许丢失？

恩，是背压错误。用的Rx2,暂时不允许丢失吧。我感觉频率也不算高吧，就300ms每条都扛不住啊。

**Comment by dhhAndroid** [comment]
项目支持kotlin吗？我这有kotlin版本的，可以直接发给你用

**Comment by YinWuteng** [comment]
> 项目支持kotlin吗？我这有kotlin版本的，可以直接发给你用

哈哈，暂时还没有在项目中引入kotlin，我在看看这个背压要怎么处理吧，谢谢。

**Comment by dhhAndroid** [comment]
你可以试试这个方法：
```java
        RxWebSocket.get("url")
                .toFlowable(BackpressureStrategy.BUFFER) //处理背压的
                .subscribe();
```
把Observable转化成支持背压策略的Flowable，在网上查一下相关用法

**Comment by YinWuteng** [comment]
> 你可以试试这个方法：
> 
> ```java
>         RxWebSocket.get("url")
>                 .toFlowable(BackpressureStrategy.BUFFER) //处理背压的
>                 .subscribe();
> ```
> 
> 把Observable转化成支持背压策略的Flowable，在网上查一下相关用法

好的。我明 天先测试一下这个效果，谢谢大佬。项目给star了
