### ISSUE TITLE
线程bug

### ISSUE THREAD

**Issue by khejing** [dhhAndroid/RxWebSocket#33]
RxWebSocketUtil.java这个文件中的getWebSocketInfo()方法，在observable已存在的情况下，是有bug的。observable没存在，用observeOn()指定了在主线程上执行，但observable已存在时却没指定。这种情况下，如果在非主线程上调用了RxWebSocket.get()方法，然后在收到websocket事件后要修改界面。那么就会是第一次没问题，但第二次就有问题，会导致app崩溃。说白了，就是会导致一个隐蔽的bug

建议不要用observeOn()，这是client要负责的事情，不应该由库负责

**Comment by dhhAndroid** [comment]
你好，缓存的Observable是已经在主线程了，应该不会出现更新UI导致崩溃的问题，这个版本的代码，我在自己公司的项目是使用的，没有出现类似问题；是不是在RxWebSocket.get()后，做了操作符变换，有的操作符变换，默认就在计算线程，不是UI线程，这也会导致subscribe之后的线程不在主线程，这个问题，你可以在单独订阅后可再做一下切换到主线程的操作。

**Comment by khejing** [comment]
谢谢回复！我的意思是observable.startWith()返回的是一个新的Observable对象，原Observable对象指定的observeOn()已经没用了。这个对象如果不指定subscribeOn()或observeOn()的话，默认subscribe()方法在哪个线程调用，subscribe()方法的参数回调就会在哪个线程执行

**Comment by dhhAndroid** [comment]
嗯嗯，一个很好的建议，我查看了一下startWith的操作符注释，startWith does not operate by default on a particular Scheduler.说的是startWith不会改变原来Observable执行的线程，也就是说原来的Observable已经指定onserveOn(mainThread())主线成后，startWith之后的Observable也是在主线程。你可以写下测试代码验证一下，如果还是不放心，你就在调用的时候，在订阅前，再指定一下主线程吧。

**Comment by dhhAndroid** [comment]
RxJava相关问题，可以加入项目下的QQ群，大家一起交流学习，非常感谢反馈问题！

**Comment by khejing** [comment]
测试代码：
``` 
    var observable: Observable<Int>? = null
    fun getMyObservable(): Observable<Int> {
        if (observable == null) {
            observable = Observable.just(1).observeOn(Schedulers.io())
        } else {
            observable = observable!!.startWith(2)
        }
        return observable!!
    }

    @Test
    fun rxjavaTest() {
        Observable.just(Unit)
                .observeOn(Schedulers.computation())
                .subscribe { _ ->
                    getMyObservable()
                            .subscribe {
                                println("first got data $it ${Thread.currentThread().name}")
                            }
                    getMyObservable()
                            .subscribe { d ->
                                println("second got data $d ${Thread.currentThread().name}")
                            }
                }
        Thread.sleep(10 * 1000)
    }
```

输出为：
> first got data 1 RxCachedThreadScheduler-1
second got data 2 RxComputationThreadPool-1
second got data 1 RxCachedThreadScheduler-1

请问我的意思说清楚了么？

**Comment by dhhAndroid** [comment]
最新版本已经修复
