### ISSUE TITLE
我如何手动控制socket的关闭和打开呢？

### ISSUE THREAD

**Issue by fan0424** [dhhAndroid/RxWebSocket#37]
如果我想在一个activity里面去手动关闭和重新打开socket该怎么做呢？

**Comment by dhhAndroid** [comment]
请查看readme、demo，以及RxJava的注销方式，都可以关闭WebSocket连接

**Comment by fan0424** [comment]
关闭后在页面不退出的情况下怎么重新打开socket？

**Comment by dhhAndroid** [comment]
重新RxWebSocket.get(url)不就行了吗？

**Comment by fan0424** [comment]
好的  谢谢  试验出来了
