### ISSUE TITLE
全局websocket关闭问题-rxjava2版本

### ISSUE THREAD

**Issue by kejunlu** [dhhAndroid/RxWebSocket#38]
请问Application里初始化的全局websocket 如何关闭？使用
Disposable disposable = RxWebSocket.get(BASE_URL).subscribe();
        if (disposable != null) {
            disposable.dispose();
        }
关闭后会自动重连，Rxjava2版本

**Comment by dhhAndroid** [comment]
你没理解对意思，是你在 调用 RxWebSocket.get(BASE_URL).subscribe()后，把返回的Disposable 存起来，然后在要关闭的时候，调用 disposable.dispose();
