### ISSUE TITLE
协议异常

### ISSUE THREAD

**Issue by liuhang1234** [dhhAndroid/RxWebSocket#39]
java.net.ProtocolException: Code must be in range [1000,5000): 10000/
这个异常是什么情况啊

**Comment by dhhAndroid** [comment]
错误说的不是很清楚呀，code必须在[1000,5000)内，你给个10000，当然就崩掉了

**Comment by turingking** [comment]
额 我也遇到了这个错误，但是我并没有给10000啊，就是再重连成功后，报这个错误，然后一直死循环了
