### ISSUE TITLE
怎样支持wss

### ISSUE THREAD

**Issue by liuweig2257** [dhhAndroid/RxWebSocket#4]
如题，怎样支持wss

**Comment by dhhAndroid** [comment]
@liuweig2257 `你好，okhttp你熟悉吗？这个WebSocket是依赖okhttp的，所以你需要自己构建一个okhttpClient，设置SSL信息：
` RxWebSocketUtil.getInstance().setClient(yourClient)`

**Comment by dhhAndroid** [comment]
@liuweig2257 通过okhttpClient设置SSL是否已经解决你的问题?

**Comment by dhhAndroid** [comment]
@liuweig2257 请查看最新readme,已经升级到1.4.0版本

**Comment by liuweig2257** [comment]
好的，谢谢。
