### ISSUE TITLE
如何保证共享一个websokcet(前后端)

### ISSUE THREAD

**Issue by iYoullloveGitHub** [dhhAndroid/RxWebSocket#40]
从目前的测试来看:
,当app网络异常,websocket 会断开,恢复网络后,再重连,后台会新建一个session,即每次断线重连,会增加seesion,断线重连到达一定次数时,后台不会挂吗?

**Comment by dhhAndroid** [comment]
这个是这样的，WebSocket一次的连接是不能重用的，okhttp内部是这样处理的，我也改不了，另外一个很出名的Java WebSocket库[Java-WebSocket](https://github.com/TooTallNate/Java-WebSocket)，也是这样的，比如断连后，是需要新开一个连接的，后台应该通过心跳机制，判断客户端是否在线，不在线的应该释放资源，这个是后台应该处理的。如果不断连，多个界面是共享一个WebSocket的，本库是这样处理的。
