### ISSUE TITLE
ping 需要自动写定时器去发ping的消息吗？

### ISSUE THREAD

**Issue by zouxianbincc** [dhhAndroid/RxWebSocket#43]
大哥，请问Ping 需要自已写定时器去ping吗？
我看代码里有这句
       // ping/pong 设置：在设置config的时候，从okhttpclient中配置：（将此client设置到上面的config中）
        OkHttpClient client = new OkHttpClient.Builder().pingInterval(6, TimeUnit.MINUTES).build();

设置了pingInterval 是不是会自动去Ping?

**Comment by dhhAndroid** [comment]
是的，自动在设置好的时间ping，不用写定时器，这是okhttp内部已经实现好的。

**Comment by zouxianbincc** [comment]
好的，谢谢🙏大哥
