### ISSUE TITLE
WebSocketSubscriber2.onMessage(text) text为空字符串时GSON解析会报错

### ISSUE THREAD

**Issue by azhu003** [dhhAndroid/RxWebSocket#44]
![image](https://user-images.githubusercontent.com/29949867/49847069-43c5d700-fe09-11e8-9fa7-983d50931ceb.png)
![image](https://user-images.githubusercontent.com/29949867/49847168-b767e400-fe09-11e8-9b6a-20cc8ceb6496.png)

**Comment by dhhAndroid** [comment]
这个正常的时候应该返回什么数据，这个应该是后台数据返回不对，导致的数据解析出错，当然本框架也没有考虑到这个问题， 我会尽快修复。
