### ISSUE TITLE
send 发送 长度 限制

### ISSUE THREAD

**Issue by zouxianbincc** [dhhAndroid/RxWebSocket#46]
有没有什么办法解决发送的数据量过大时，会超出限制，进而引起程序崩溃了。
有没有办法解决？

**Comment by dhhAndroid** [comment]
这个问题我没有遇见过，是导致内存溢出了吗 ？发送大文件我感觉还是不推荐

**Comment by zouxianbincc** [comment]
是内存溢出了。也不算很大，就是一个订单的详情内容

**Comment by dhhAndroid** [comment]
这个不应该啊，曾经有开发者用这个库，上传视频文件都是可以的

**Comment by zouxianbincc** [comment]
那我再试试是不是我字符串格式的原因
