### ISSUE TITLE
javax.net.ssl.SSLException 部分手机会出现这个问题

### ISSUE THREAD

**Issue by dalingge** [dhhAndroid/RxWebSocket#47]
io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | javax.net.ssl.SSLException: Read error: ssl=0xc17bda80: I/O error during system call, Software caused connection abort
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
	at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onError(ObservableCreate.java:73)
	at com.base.library.b.b.b$a$1.onFailure(RxWebSocketUtil.java:361)
	at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:571)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:216)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:784)
Caused by : javax.net.ssl.SSLException: Read error: ssl=0xc17bda80: I/O error during system call, Software caused connection abort
	com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
	com.android.org.conscrypt.SslWrapper.read(SslWrapper.java:384)
	com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:541)
	okio.o$2.read(Okio.java:140)
	okio.a$2.read(AsyncTimeout.java:237)
	okio.s.b(RealBufferedSource.java:68)
	okio.s.a(RealBufferedSource.java:61)
	okio.s.i(RealBufferedSource.java:74)
	okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:117)
	okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
	okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
	okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)

**Comment by dhhAndroid** [comment]
你是不是用的wss，这个应该是ssl协议相关的问题

**Comment by kejunlu** [comment]
> 你是不是用的WSS，这个应该是SSL协议相关的问题
配置了TLS相关的setSSLSocketFactory，部分手机还是会这样 @dhhAndroid

**Comment by dhhAndroid** [comment]
在okhttp项目下，查看一下相关问题吧，这个属于兼容性问题。

**Comment by dalingge** [comment]
谢谢 我已经解决

**Comment by dhhAndroid** [comment]
> 谢谢 我已经解决

请问是什么问题导致的？ 我收录一下。

**Comment by dalingge** [comment]
我们这边后台长时间没有给前端发送数据会主动把websocket断开，照成了部分手机(大部分是华为)各种莫名其妙ssl错误，报错后rxjava取消订阅但是请求线程还在执行，执行中抛出异常，就会导致这种问题！io.reactivex.exceptions.UndeliverableException 官方解决办法就是在Application 加错误拦截器
        RxJavaPlugins.setErrorHandler(new Consumer<Throwable>() {
            @Override
            public void accept(Throwable throwable) throws Exception {
                try {
                    if (throwable instanceof UndeliverableException) {
                        throwable = throwable.getCause();
                    }
                    if (throwable instanceof IOException) {
                        // fine, irrelevant network problem or API that throws on cancellation
                        return;
                    }
                    if (throwable instanceof InterruptedException) {
                        // fine, some blocking code was interrupted by a dispose call
                        return;
                    }
                    if ((throwable instanceof NullPointerException) || (throwable instanceof IllegalArgumentException)) {
                        // that's likely a bug in the application
                        Thread.currentThread().getUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), throwable);
                        return;
                    }
                    if (throwable instanceof IllegalStateException) {
                        // that's a bug in RxJava or in a custom operator
                        Thread.currentThread().getUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), throwable);
                        return;
                    }
                    XLog.w("Undeliverable exception received, not sure what to do", throwable);
                } catch (Exception e) {
                    XLog.w("ErrorHandler捕获未知类型异常", e);
                }
            }
        });

我这个可能也不是正确的解决办法
