### ISSUE TITLE
断网然后重新连网会一直cancel重连

### ISSUE THREAD

**Issue by ccxbd** [dhhAndroid/RxWebSocket#49]
log：02-18 09:28:00.717 27760-27760/com.giada.gdsm D/TestService: 重连
02-18 09:28:00.719 27760-27786/com.giada.gdsm D/GDSM: ws://www.xxx:8081/api/MessageRelease --> cancel 
02-18 09:28:00.751 27760-28074/com.giada.gdsm D/GDSM: ws://www.xxx:8081/api/MessageRelease --> onOpen
02-18 09:28:00.752 27760-27760/com.giada.gdsm D/TestService: onOpen1:
02-18 09:28:00.763 27760-28074/com.giada.gdsm E/GDSM: java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)/api/MessageRelease
02-18 09:28:02.799 27760-27760/com.giada.gdsm D/TestService: 重连
02-18 09:28:02.801 27760-28074/com.giada.gdsm D/GDSM: ws://www.xxx:8081/api/MessageRelease --> cancel 
02-18 09:28:02.828 27760-27786/com.giada.gdsm D/GDSM: ws://www.xxx:8081/api/MessageRelease --> onOpen
02-18 09:28:02.829 27760-27760/com.giada.gdsm D/TestService: onOpen1:
02-18 09:28:02.838 27760-27786/com.giada.gdsm E/GDSM: java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)/api/MessageRelease
02-18 09:28:04.874 27760-27760/com.xxx D/TestService: 重连
02-18 09:28:04.877 27760-27786/com.giada.gdsm D/GDSM: ws://www.xxx:8081/api/MessageRelease --> cancel 
02-18 09:28:04.904 27760-28074/com.giada.gdsm D/GDSM: ws://www.xxx:8081/api/MessageRelease --> onOpen
02-18 09:28:04.905 27760-27760/com.giada.gdsm D/TestService: onOpen1:
02-18 09:28:04.916 27760-28074/com.giada.gdsm E/GDSM: java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)/api/MessageRelease

**Comment by dhhAndroid** [comment]
我看了一下，里面有这个错误 ava.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)，应该是这个错误导致连接失败的，你和你们后端沟通一下
