### ISSUE TITLE
rxjava2 手动关闭不成功

### ISSUE THREAD

**Issue by zouxianbincc** [dhhAndroid/RxWebSocket#50]
//注销方法。但是并不能关闭此连接
        Disposable disposable = RxWebSocket.get(url).subscribe();
        if (disposable != null && !disposable.isDisposed()) {
            disposable.dispose();
        }
操作如下，连接成后，再断开网络，会自动重新连接，一直回调
@Override
            protected void onReconnect() {
                super.onReconnect();
}
然后 手动调用注销方法，但是并不能结束掉这个连接，还会一直回调重连机制

**Comment by dhhAndroid** [comment]
不是这样注销的，是你在调用RxWebSocket.get(url)那里订阅后，会返回一个 disposable，你要用这个disposable调用取消订阅的方法，这个是RxJava2相关的知识，你可以在网上查一下

**Comment by dhhAndroid** [comment]
### 类似下面的代码：

```java
    private Disposable mDisposable;

    public void openWebSocket() {
        mDisposable = RxWebSocket.get("your url");
                .subscribe(new WebSocketSubscriber() {
            @Override
            protected void onMessage(String text) {

            }

            @Override
            protected void onReconnect() {
                Log.d("MainActivity", "重连");
            }
        });
    }

    public void  closeWebSocket() {
        if (mDisposable != null) {
            mDisposable.dispose();
        }
    }
```

**Comment by zouxianbincc** [comment]
mDisposable = RxWebSocket.get("your url");
                .subscribe(new WebSocketSubscriber() {
            @Override
            protected void onMessage(String text) {

            }

            @Override
            protected void onReconnect() {
                Log.d("MainActivity", "重连");
            }
        });

是得不到 Disposable 的
 因为 public final void subscribe(Observer<? super T> observer)

**Comment by dhhAndroid** [comment]
我懂你意思了，你把这个 WebSocketSubscriber，作为一个成员变量，这样用，方案不一样：
```java
    private WebSocketSubscriber webSocketSubscriber;

    public void openWebSocket() {
        webSocketSubscriber = new WebSocketSubscriber() {
            @Override
            protected void onMessage(String text) {

            }

            @Override
            protected void onReconnect() {
                Log.d("MainActivity", "重连");
            }
        };
        RxWebSocket.get("your url")
                .subscribe(webSocketSubscriber);
    }

    public void closeWebSocket() {
        if (webSocketSubscriber != null) {
            webSocketSubscriber.dispose();
        }
    }

```

**Comment by skyseraph** [comment]
> 我懂你意思了，你把这个 WebSocketSubscriber，作为一个成员变量，这样用，方案不一样：
> ```

当用这种方式dispose，close等方法都不会再调用，业务层还得自己处理close逻辑~

**Comment by xiejinsorry** [comment]
我想问一下，这样做 能真正断开 后台的连接吗？会不会后台 实际还连接着，只是前端没有了监听器而已？
