### ISSUE TITLE
每发送一次，就会增加一个回调，建议判断如果请求相同，不增加回调

### ISSUE THREAD

**Issue by mingxin-yang** [dhhAndroid/RxWebSocket#53]
每使用一次**asyncSend**发送一个以前发送的请求，使用
```
RxWebSocket.get()
            .compose(RxLifecycle.with(MainActivity.this).<WebSocketInfo>bindToLifecycle())
            .subscribe(new websocketsubscriber(){})
```
就会多一次回调，返回来的值相同，而且是连续返回

**Comment by dhhAndroid** [comment]
asyncSend发送方式，是为了只发送而不关心接收数据而设计的，如果要监听这个WebSocket的数据，这时候WebSocket连接已经打开，直接调用send方法发送消息就可以了，send方法用的是已经存在的消息通道，async是先获取消息通道，也就是要先确保消息通道是连接的，然后再发送。你这种情况用send就行。

**Comment by mingxin-yang** [comment]
我试了使用send，也是不行，每发送一次收到的就叠加一次，有没有方法把以前发送的回调销毁

**Comment by dhhAndroid** [comment]
如果方便的话，你把你们的url，和发送参数，发我邮箱一下，我调试一下，看看是什么情况。你说的情况，没遇到过。应该是你们服务端有问题。。。
我的邮箱：dhhmaster@gmail.com

**Comment by mingxin-yang** [comment]
给你发过去了mingxinyang2017@gmail.com

**Comment by mingxin-yang** [comment]
@dhhAndroid 有结果了吗

**Comment by dhhAndroid** [comment]
@mingxin-yang 我试了，但是我这边send 的时候，都没有数据发给我，不知道什么情况。

**Comment by mingxin-yang** [comment]
@dhhAndroid login 的json串发对了吗，ECHO 之后有个空格，\r\n 前面有个空格
