### ISSUE TITLE
该项不能主动接收到服务端的消息，例如连接成功后，服务端自己发送数据给前端

### ISSUE THREAD

**Issue by topCard** [dhhAndroid/RxWebSocket#54]
这个不像是socket那样可以接收信息，一定要发送一个请求给服务端才可以接收服务端的信息。
那样就跟http请求那样了，前端发一个请求服务端回一个消息。那服务端主动发送给客户端的消息就接收不到了。

**Comment by dhhAndroid** [comment]
不是这样的啊，建立连接后，会在onMessage回调里接收服务端推送的消息，如果不能接收服务端推的消息，那这个RxWebSocket还有什么用。。。

**Comment by topCard** [comment]
我们这边后台的问题，其实是可以的，很好用的框架，赞！谢谢小哥的回复！！！！！！！

**Comment by topCard** [comment]
> 不是这样的啊，建立连接后，会在onMessage回调里接收服务端推送的消息，如果不能接收服务端推的消息，那这个RxWebSocket还有什么用。。。

找到问题了，是我们这边后台的问题，是可以的，很好用的一个框架，赞！！！谢谢小哥的回复！

**Comment by dhhAndroid** [comment]
谢谢支持，那问题我就关闭了
