### ISSUE TITLE
onResume方法里重连不起作用问题咨询

### ISSUE THREAD

**Issue by ender115** [dhhAndroid/RxWebSocket#57]
大佬
我在onResume重连，onOpen方法会成功，但是我用之前建立连接获取到的mWebSocket来发送消息，发送不成功，是不是要用onResume里面onOpen方法返回的webSocket来发送消息才行。因为比较晚了，后台已经下班，没法调试，所以先来问一下，明天再自己试试

**Comment by dhhAndroid** [comment]
是的，你如果用onOpen里的WebSocket的发消息，每次重连后，都要用把这个新值赋值到mWebSocket上，因为每次重连都是一个新的连接，要用新的mWebSocket引用发送消息
