### ISSUE TITLE
设置发送心跳包时间以及内容

### ISSUE THREAD

**Issue by androidheweidong** [dhhAndroid/RxWebSocket#58]
OkHttpClient client = new OkHttpClient.Builder().pingInterval(1, TimeUnit.SECONDS).build();
这句话是设置心跳包发送时间的吗？可是我我想设置发送的内容。不知道在哪里设置。需要我自己写吗？还是您已经写好了，麻烦您告诉一下~

**Comment by dhhAndroid** [comment]
这是方式是，WebSocket自带的 ping/pong 心跳机制，如果是你们后台自定义的心跳机制，你就要和后台沟通了，这边是在确保连接打开后，直接调用 **RxWebSocket.send()** 方法就可以了

**Comment by androidheweidong** [comment]
好的，那就是我自己写一个定时器 然后调用send（）方式就可以了是吧
