### ISSUE TITLE
websocket在台湾连不上

### ISSUE THREAD

**Issue by ender115** [dhhAndroid/RxWebSocket#64]
大佬，请教一个问题，我用这个框架以后在大陆连socket是没问题的，但是在台湾连不上，因为没有那边的网络环境，暂时不知道什么原因，这个框架应该没有这方面的限制吧，也可能是我们服务端的原因

**Comment by dhhAndroid** [comment]
这个框架肯定不会做这个限制，网络框架是基于okhttp的，不会有网络限制的，这个问题是由于地区和服务器的问题，让你们后台解决吧，应该需要在国外的服务器部署你们的服务端。
