### ISSUE TITLE
ContextImpl can't cast Activity !

### ISSUE THREAD

**Issue by kevinStrange** [dhhAndroid/RxWebSocket#66]
上下文转换有问题，当使用上下文时，程序会报错 RxLifecycle.with(mContext)

**Comment by dhhAndroid** [comment]
说明这个 mContext 不是 Activity 实例 ，比如service，ContextWrapper都不是Activity实例，你打印一下这个 mContext 的字节码名字就可以知道是什么了。另外 建议使用 [RxLife](https://github.com/dhhAndroid/RxLife) 代替 RxLifecycle。
