### ISSUE TITLE
这个同种类型的消息覆盖肯定不行的

### ISSUE THREAD

**Issue by xiejinsorry** [dhhAndroid/RxWebSocket#68]
比如说 k线数据，订阅的时候返回的都是 一条一条的， 如果你覆盖了， 那数据就丢失了
另外 就算不是k线， 如果socket 的数据类型很多，那肯定没办法直接泛型数据，我这里都是直接设置成 String 然后再解析的， 按照 消息覆盖 ， 那我岂不是很多消息不管什么类型都直接覆盖了

**Comment by dhhAndroid** [comment]
消息没有做覆盖操作，WebSocketInfo每次都是new出来的实例，如果一个url推送的数据类型是可以的，那就原始String接收，再按不同的code或者策略去解析
