### ISSUE TITLE
消息一多就会卡顿

### ISSUE THREAD

**Issue by xiejinsorry** [dhhAndroid/RxWebSocket#69]
卡顿 咋办？

**Comment by dhhAndroid** [comment]
首先你应该贴一下你出现卡顿情况的调用代码；
通过你上一个问题，大致可以判断是因为你在解析数据的时候是在主线程解析的，比如gson.formJson方法，如果数据很大，并且数据频繁发送，在主线程反序列化，就会造成卡顿

**Comment by xiejinsorry** [comment]
不对 我代码是这样的   disposable = MyCommonSocketClient()
        RxWebSocket.get(Constants.IM_SOCKET)
                .observeOn(Schedulers.io())
                .subscribeOn(Schedulers.io())
                .subscribe(disposable!!)  我都是在 io 线程 执行 然后用handler 更新ui

**Comment by xiejinsorry** [comment]
> 首先你应该贴一下你出现卡顿情况的调用代码；
> 通过你上一个问题，大致可以判断是因为你在解析数据的时候是在主线程解析的，比如gson.formJson方法，如果数据很大，并且数据频繁发送，在主线程反序列化，就会造成卡顿

不对 我代码是这样的 disposable = MyCommonSocketClient()
RxWebSocket.get(Constants.IM_SOCKET)
.observeOn(Schedulers.io())
.subscribeOn(Schedulers.io())
.subscribe(disposable!!) 我都是在 io 线程 执行 然后用handler 更新ui

**Comment by dhhAndroid** [comment]
MyCommonSocketClient方法里的代码我看下

**Comment by dhhAndroid** [comment]
长时间未回应，先关闭Issue了
