### ISSUE TITLE
关于断开连接使用的问题(can't disconnect websocket)

### ISSUE THREAD

**Issue by kong-jing** [dhhAndroid/RxWebSocket#7]
这里断开连接不能使用。
[断开连接](https://github.com/dhhAndroid/RxWebSocket/tree/2.x#rxjava的注销方式就可以取消订阅-优雅地处理rxjava注销请查看我另外一个项目rxlifecycle)

**Comment by kong-jing** [comment]
在 RxJava2 中，由于已经存在了 org.reactivestreams.subscription 这个类，为了避免名字冲突将原先的 rx.Subscription 改名为 io.reactivex.disposables.Disposable。

**Comment by dhhAndroid** [comment]
@kong-jing 你好,非常感谢你的指正,这个属于readme书写错误,先写的RxJava1,后写RxJava2的时候readme没注意,多谢指正,新发布了1.4.0版本.请使用新版本.
