### ISSUE TITLE
不行啊，虽然是可以新开dispose，但是我看了本质还是同一个连接啊

### ISSUE THREAD

**Issue by xiejinsorry** [dhhAndroid/RxWebSocket#71]
我确定是同一个连接，返回的数据， 还返回了其他连接里订阅的数据，这样明显不对啊

**Comment by dhhAndroid** [comment]
应该是使用不当导致的，框架内部会只会缓存哦onOpen事件

**Comment by clj12081103** [comment]
确实，dispose后重新订阅，原来的订阅内容还在，偶尔出现不是必然出现

**Comment by clj12081103** [comment]
> 应该是使用不当导致的，框架内部会只会缓存哦onOpen事件

请问怎么不缓存onOpen事件

**Comment by dhhAndroid** [comment]
目前不支持
