### ISSUE TITLE
disposable.dispose()方法不回调onclose吗

### ISSUE THREAD

**Issue by clj12081103** [dhhAndroid/RxWebSocket#74]

**Comment by dhhAndroid** [comment]
你好，我看了一下代码，的确在调用dispose的时候，没有回调 onClose。当时的想法是手动调用dispose的话，如果想要做其他操作，就直接一起做了，就没有回调onClose

**Comment by clj12081103** [comment]
好的，多谢回复。再请问一下，调用dispose()后是立即关闭socket吗？

**Comment by dhhAndroid** [comment]
这个有点复杂，内部有缓存机制，简单的说，就是调用dispose只会关闭当前的WebSocket监听，当这个url的WebSocket的监听器个数减到0的时候，才会关闭WebSocket。
