### ISSUE TITLE
急！！！！长时间熄屏或者其他情况无消息

### ISSUE THREAD

**Issue by xiejinsorry** [dhhAndroid/RxWebSocket#76]
我自己没出现过， 可能我用得比较少吧
听人说，经常出现还连着，但是收不到消息，或者断开了，再也连不上的情况，我也不知道是怎么出现的

**Comment by dhhAndroid** [comment]
这些问题一般是保活相关的，程序都死了，WebSocket自然就没了。你可以看看保活相关的策略。

**Comment by xiejinsorry** [comment]
我知道可能被系统回收了，但是再次进来 ，连不上了怎么解决？不会自动重连了

**Comment by kfy18434860320** [comment]
我也遇到这个问题了，从后台回来 就不重连了
