### ISSUE TITLE
timeout 连接 开销有点大

### ISSUE THREAD

**Issue by xiejinsorry** [dhhAndroid/RxWebSocket#77]
如题，假设一个连接一只保持着，但是暂时没有信息发送过来， 就会一直重连一直重连， 内部不是用ping pong的形式，而是判断没有新的消息发送过来就重连，这样的话感觉开销有点大，一直在重连重连

**Comment by dhhAndroid** [comment]
你好，timeout机制只是一种保险措施，你可以在使用的时候把 timeout时间设置长有点，比如一天，一周等，就没有timeout导致的重连问题了。
