### ISSUE TITLE
我想一个url 多个连接咋办

### ISSUE THREAD

**Issue by xiejinsorry** [dhhAndroid/RxWebSocket#81]
我改变了map的key，变成url+tag，好像还是共用了一个连接

**Comment by xiejinsorry** [comment]
我吧share 去掉了貌似可以了，不知道会有什么影响不？

**Comment by xiejinsorry** [comment]
好像还是不行啊 ，而且会有问题，有些数据都拿不到了，如果 我所有地方共用一个连接，那是没问题，但是数据刷新太快怕会还有频率方面的问题

**Comment by dhhAndroid** [comment]
share去掉后，也要把-Observable缓存到map里的方法也去掉
