### ISSUE TITLE
WebSocket连接过程中，切换wifi，重连之后再dispose无法断开WebSocket

### ISSUE THREAD

**Issue by wywy4pm** [dhhAndroid/RxWebSocket#84]
重新连接wifi之后，发现websocket调用close 3000，执行了--> cancel日志，但是没有回调WebSocketListener的onClosed方法，服务端也没有收到断开的消息

**Comment by dhhAndroid** [comment]
重连是自动触发的逻辑，不是人为主动调用关闭方法，所以不会回调onClosed方法
