### ISSUE TITLE
接锅回调存在多个

### ISSUE THREAD

**Issue by Alexxiaopang** [dhhAndroid/RxWebSocket#85]
如题，使用的是：
  RxWebSocket.get(wssurl_A)
                    .compose(AndroidLifecycle.createLifecycleProvider(ChatFragment.this).bindUntilEvent(Lifecycle.Event.ON_DESTROY))
                    .subscribeOn(Schedulers.io())
                    .observeOn(AndroidSchedulers.mainThread())
                    .subscribe(new WebSocketSubscriber() 
wssurl_A连接已经连接上，回调进行显示操作
这时候使用 Disposable mdisposable = RxWebSocket.get(wssurl_A).subscribe(); mdisposable.dispose();注销A
wssurl_B链接
  RxWebSocket.get(wssurl_A)
                    .compose(AndroidLifecycle.createLifecycleProvider(ChatFragment.this).bindUntilEvent(Lifecycle.Event.ON_DESTROY))
                    .subscribeOn(Schedulers.io())
                    .observeOn(AndroidSchedulers.mainThread())
                    .subscribe(new WebSocketSubscriber() 
wssurl_B连接已经连接上，回调进行显示操作（和A回调一样）

如果服务器发送东西过来，回调会存在两个

**Comment by dhhAndroid** [comment]
注销的方式不对，这个是属于RxJava的用法问题，当你开启WebSocketA连接后，会返回 一个disposable，你要调用这个 disposable.dispose()方法，不是使用  Disposable mdisposable = RxWebSocket.get(wssurl_A).subscribe(); mdisposable.dispose();来注销
